version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: hostinger-test
    ports:
      - "8080:8080"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
